// Code generated by mockery v2.17.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeQuizServer is an autogenerated mock type for the UnsafeQuizServer type
type UnsafeQuizServer struct {
	mock.Mock
}

// mustEmbedUnimplementedQuizServer provides a mock function with given fields:
func (_m *UnsafeQuizServer) mustEmbedUnimplementedQuizServer() {
	_m.Called()
}

type mockConstructorTestingTNewUnsafeQuizServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafeQuizServer creates a new instance of UnsafeQuizServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafeQuizServer(t mockConstructorTestingTNewUnsafeQuizServer) *UnsafeQuizServer {
	mock := &UnsafeQuizServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
